# Generated by Django 5.2 on 2025-04-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('inn', models.CharField(max_length=12)),
            ],
        ),
    ]
