# Generated by Django 5.2 on 2025-04-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_phonecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='operator',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='phonecode',
            name='region',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
